# Docker compose script to bring up Postgres
# This will bring up the db to localhost:5432

# Reference this: https://github.com/felipewom/docker-compose-postgres/
services:
  database:
    image: 'postgres:18'
    ports:
      - 5432:5432
    env_file:
    - "db-creds.env"
    volumes:
      - "./db:/var/lib/postgresql/18/docker"
      - "./init-db.sql:/docker-entrypoint-initdb.d/init.sql"
  web_server:
    build: .
    ports:
      - 6767:5000
    depends_on:
      - database
    restart: always
